// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCi72rQs1nVBCkoJfF-CQi8jMt7j5jo8PQ',
    appId: '1:565716447051:web:ddc6642a2d1598d28b82ce',
    messagingSenderId: '565716447051',
    projectId: 'coffeeshopauthe',
    authDomain: 'coffeeshopauthe.firebaseapp.com',
    storageBucket: 'coffeeshopauthe.appspot.com',
    measurementId: 'G-9GE8Q24H8P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABiA0V89Ciyd7gOmSBBvGHvb3r3JSPKUQ',
    appId: '1:565716447051:android:b486054790667c3e8b82ce',
    messagingSenderId: '565716447051',
    projectId: 'coffeeshopauthe',
    storageBucket: 'coffeeshopauthe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPEqrAdAco4bisgdzSr6kqIvqrghrBiXU',
    appId: '1:565716447051:ios:152ee0fce9fe308e8b82ce',
    messagingSenderId: '565716447051',
    projectId: 'coffeeshopauthe',
    storageBucket: 'coffeeshopauthe.appspot.com',
    iosBundleId: 'com.example.coffeeshop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPEqrAdAco4bisgdzSr6kqIvqrghrBiXU',
    appId: '1:565716447051:ios:7ef2593288c76eff8b82ce',
    messagingSenderId: '565716447051',
    projectId: 'coffeeshopauthe',
    storageBucket: 'coffeeshopauthe.appspot.com',
    iosBundleId: 'com.example.coffeeshop.RunnerTests',
  );
}
